### PR TITLE
Fix parent field name different from 'parent'

### PR DESCRIPTION
**Pull request by singleton11**
If PolymorphicTreeForeignKey field name has name which different from 'parent' there was an error in admin
Added test for case above
Actualized tox and travis configs
Added step-by-step instruction to readme how to run tests
Adjusted supported version list in readme

### CODE REVIEW

**Comment by singleton11** [comment]
Added possibility to make validation before move node in admin through ``can_be_moved`` method of ``PolymorphicMPTTModel`` overriding. This method calls in admin, and if there are exceptions during execution, error response returns

**Comment by vdboor** [comment]
Thanks for this wonderful work!

**Comment by vdboor** [comment]
I do wonder, is `can_be_moved()` needed? For example, there is already `can_have_children()` which does about the same thing. Where are you using that hook for?

**Comment by vdboor** [comment]
@singleton11 FYI, I've renamed`can_move_to()` to `validate_move_to()`
Since we can limit the children types now, would you still need `validate_move_to()` to exist?
Thanks for letting me know!

**Comment by singleton11** [comment]
@vdboor, I promise, I will send different features as separate PRs next time ;-)

mptt doesn't call ``clean()`` to check, if validation error occurs, when ``move()`` executed. Example case: tree of attendees of conference. Attendees have managers. However attendee and his manager have to be from the same conference.

**Pull request merged**
